# Generated by Django 5.1.2 on 2024-11-11 07:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения: ')),
                ('age', models.CharField(blank=True, editable=False, max_length=3, verbose_name='Возраст')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ребенок',
                'verbose_name_plural': 'Дети',
            },
        ),
        migrations.CreateModel(
            name='GroupType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Тип группы',
                'verbose_name_plural': 'Типы групп',
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('location', models.CharField(max_length=100, verbose_name='Город')),
                ('district', models.CharField(max_length=100, verbose_name='Район')),
                ('subscription_amount', models.IntegerField(default=6900, verbose_name='Стоимость абонемента')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный клиент')),
            ],
            options={
                'verbose_name': 'Родитель',
                'verbose_name_plural': 'Родители',
            },
        ),
        migrations.CreateModel(
            name='TrialRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=100, verbose_name='ФИО родителя')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Телефон')),
                ('child_name', models.CharField(max_length=100, verbose_name='ФИО ребенка')),
                ('child_age', models.IntegerField(verbose_name='Возраст ребенка')),
                ('preferred_time', models.CharField(max_length=100, verbose_name='Предпочитаемое время')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('processed', 'В обработке'), ('confirmed', 'Подтверждена'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Заявка на пробное',
                'verbose_name_plural': 'Заявки на пробное',
            },
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата пропуска')),
                ('status', models.CharField(choices=[('missed', 'Пропущено'), ('scheduled', 'Запланирована отработка'), ('completed', 'Отработано')], default='missed', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='childparent_crm.child', verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Пропуск',
                'verbose_name_plural': 'Пропуски',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group_type', models.CharField(blank=True, max_length=100, verbose_name='Тип группы')),
                ('day_of_week', models.CharField(max_length=20, verbose_name='День недели')),
                ('time_start', models.TimeField(verbose_name='Время начала')),
                ('time_end', models.TimeField(blank=True, verbose_name='Время окончания')),
                ('students', models.ManyToManyField(blank=True, related_name='groups', to='childparent_crm.child')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'db_table': 'childparent_crm_group',
            },
        ),
        migrations.CreateModel(
            name='MakeupClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('makeup_date', models.DateField(verbose_name='Дата отработки')),
                ('time_slot', models.CharField(choices=[('9:00', '9:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('12:00', '12:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00'), ('18:00', '18:00')], max_length=10, verbose_name='Время')),
                ('status', models.CharField(choices=[('scheduled', 'Запланирована'), ('completed', 'Выполнена'), ('cancelled', 'Отменена')], default='scheduled', max_length=20, verbose_name='Статус')),
                ('reason', models.TextField(blank=True, verbose_name='Причина пропуска')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('absence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='childparent_crm.absence', verbose_name='Пропуск')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='childparent_crm.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Отработка',
                'verbose_name_plural': 'Отработки',
                'ordering': ['makeup_date', 'time_slot'],
            },
        ),
        migrations.AddField(
            model_name='child',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='childparent_crm.parent'),
        ),
        migrations.CreateModel(
            name='ParentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='childparent_crm.parent')),
            ],
            options={
                'verbose_name': 'Комментарий к родителю',
                'verbose_name_plural': 'Комментарии к родителям',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('payment_type', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Карта'), ('transfer', 'Перевод')], max_length=50, verbose_name='Тип оплаты')),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='childparent_crm.parent')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
            },
        ),
    ]
