# Generated by Django 5.1.2 on 2024-11-02 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childparent_crm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='type',
        ),
        migrations.AddField(
            model_name='group',
            name='group_type',
            field=models.CharField(default='-', max_length=100, verbose_name='Тип группы'),
        ),
        migrations.AlterField(
            model_name='group',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='group',
            table='childparent_crm_group',
        ),
    ]
