# Generated by Django 5.1.2 on 2024-11-11 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childparent_crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlySubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('lessons_count', models.IntegerField()),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Не оплачено'), ('PARTIAL', 'Частично оплачено'), ('PAID', 'Полностью оплачено')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='childparent_crm.parent')),
            ],
        ),
    ]
