# Generated by Django 5.1.2 on 2024-11-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childparent_crm', '0003_alter_group_time_end_parentcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='subscription_amount',
            field=models.IntegerField(default=6900, verbose_name='Стоимость абонемента'),
        ),
    ]
