# Generated by Django 5.1.2 on 2024-11-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childparent_crm', '0005_child_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='age',
            field=models.CharField(blank=True, editable=False, max_length=3, verbose_name='Возраст'),
        ),
    ]
