# Generated by Django 5.1.2 on 2024-11-06 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childparent_crm', '0006_alter_child_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата пропуска')),
                ('status', models.CharField(choices=[('missed', 'Пропущено'), ('scheduled', 'Запланирована отработка'), ('completed', 'Отработано')], default='missed', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='childparent_crm.child', verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Пропуск',
                'verbose_name_plural': 'Пропуски',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MakeupClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('makeup_date', models.DateField(verbose_name='Дата отработки')),
                ('time_slot', models.CharField(choices=[('9:00', '9:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('12:00', '12:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00'), ('18:00', '18:00')], max_length=10, verbose_name='Время')),
                ('status', models.CharField(choices=[('scheduled', 'Запланирована'), ('completed', 'Выполнена'), ('cancelled', 'Отменена')], default='scheduled', max_length=20, verbose_name='Статус')),
                ('reason', models.TextField(blank=True, verbose_name='Причина пропуска')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('absence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='childparent_crm.absence', verbose_name='Пропуск')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='childparent_crm.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Отработка',
                'verbose_name_plural': 'Отработки',
                'ordering': ['makeup_date', 'time_slot'],
            },
        ),
    ]
